version: 2.0

jobs:
  checkout_build:
    docker:
      - image: golang:1.10-stretch
      - image: rabbitmq:3.6
    working_directory: /go/src/github.com/nuvi/go-classifier
    steps:
      - checkout

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/go/src/github.com/nuvi/go-classifier"
      - run:
          name: Install Golint
          command: go get -u golang.org/x/lint/golint
      - run:
          name: Install godep
          command: go get -u github.com/tools/godep
      - run:
          name: Run fmt and vet
          command: |
            golint -set_exit_status . && \
            go fmt && \
            go vet
      - run:
          name: Run Utilities Tests
          command: go test ./utilities
      - run:
          name: Build Go Binarys
          command: GOOS=linux go generate -v
      - persist_to_workspace:
          root: /go/src/github.com/nuvi/go-classifier
          paths:
            - go-classifier
            - Dockerfile
            - Procfile

  build_image:
    machine:
      enabled: true
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Build Docker Image
          command: |
            docker build -t nuvi/go-classifier:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push nuvi/go-classifier:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
      - persist_to_workspace:
          root: /tmp
          paths:
            - Procfile

  deploy_image_stage:
    docker:
      - image: nuvi/deis-workflow-cli:v2.18.0
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Login to Deis Whiskey
          command: deis login https://deis.whiskey.deis.nuviapp.com --username $DEIS_WHISKEY_USER --password $DEIS_WHISKEY_PASSWORD
      - run:
          name: Deis pull image
          command: deis pull nuvi/go-classifier:$CIRCLE_BRANCH-$CIRCLE_PREVIOUS_BUILD_NUM -a classifier-stage

  deploy_image_prod:
    docker:
      - image: nuvi/deis-workflow-cli:v2.18.0
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Login to Deis Whiskey
          command: deis login https://deis.whiskey.deis.nuviapp.com --username $DEIS_WHISKEY_USER --password $DEIS_WHISKEY_PASSWORD
      - run:
          name: Deis pull image
          command: deis pull nuvi/go-classifier:$CIRCLE_BRANCH-$CIRCLE_PREVIOUS_BUILD_NUM -a classifier-prod

workflows:
  version: 2
  build:
    jobs:
      - checkout_build
      - build_image:
          filters:
            branches:
              only:
                - master
                - prod
          requires:
            - checkout_build
      - deploy_image_stage:
          filters:
            branches:
              only:
                - master
          requires:
            - build_image
      - deploy_image_prod:
          filters:
            branches:
              only:
                - prod
          requires:
            - build_image